version: '3'

services:
    db:
        image: mariadb:10.3.9
        ports:
            - 3307:3306
        volumes:
            - data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=manager
            - MYSQL_PASSWORD=secret
    web:
        image: wordpress:latest
        depends_on:
            - db
        volumes:
            - ./target:/var/www/html
            - ./static:/var/www/html_static
        environment:
            - WORDPRESS_DB_USER=manager
            - WORDPRESS_DB_PASSWORD=secret
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DEBUG=false
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "tapinpack.tictap.me:host-gateway"
    wpcli:
        container_name: wpcli
        depends_on:
            - web
        image: wordpress:cli
        user: 1000:1000
        command: tail -f /dev/null
        volumes:
            - ./target:/var/www/html
        environment:
            - WORDPRESS_DB_USER=manager
            - WORDPRESS_DB_PASSWORD=secret
            - WORDPRESS_DB_HOST=db
    proxy:
        image: nginx:1.19.10-alpine
        ports:
            - 81:81
            - 80:80
            - 443:443
        volumes:
            - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy/conf/conf.d/:/etc/nginx/conf.d/
            - ./proxy/certs:/etc/nginx/certs
            - ./static:/var/www/html_static
        depends_on:
            - web

volumes:
    data:
